### ISSUE TITLE
'Player' object has no attribute 'register_properties_handler'

### ISSUE THREAD

**Issue by hugosenari** [wistful/pympris#11]
Hi,

Nice project.

For some reason I can run example to set properties change handler.
```
mp.player.register_properties_handler(handle_properties_changes)
AttributeError: 'Player' object has no attribute 'register_properties_handler'
```

[]'s
Hugo

**Comment by wistful** [comment]
Hi @hugosenari,
The method `register_properties_handler` currently is available only in dev version.
You can install dev version from repository using pip: `pip install git+https://github.com/wistful/pympris.git`
